In [28]:
import json
from paddlenlp.data import JiebaTokenizer,Vocab
from setting import TEST_DICT,TEST_JSON_PATH,SELF_DICT
from paddlenlp.embeddings import TokenEmbedding

# 构建词典

In [4]:
vocab = Vocab.load_vocabulary(TEST_DICT,unk_token='[UNK]',pad_token='[PAD]')

# 构建分词器

In [6]:
tokenizer = JiebaTokenizer(vocab=vocab)

# 读取数据集

In [14]:
class Reader:
    def __init__(self,json_path,encoding='utf-8'):
        with open(json_path,encoding=encoding) as file:
            self.data = file.readlines()
    def __getitem__(self, item):
        return json.loads(self.data[item])


In [15]:
reader = Reader(TEST_JSON_PATH)

In [25]:
line = reader[0]
fact,law = line['fact'],line['meta']['relevant_articles'][0]

# 测试分词
效果还行

In [38]:
tokenizer.cut(fact)

['攸县',
 '人民',
 '检察院',
 '指控',
 '，',
 '2017年',
 '3月2日',
 '19时',
 '许',
 '，',
 '被告人',
 '吴某某',
 '到',
 '攸县',
 '江桥',
 '街道',
 '“',
 '窝里',
 '人',
 '”',
 '饭店',
 '找易',
 '某',
 '谈论',
 '事情',
 '时',
 '，',
 '双方',
 '发生',
 '口角',
 '，',
 '吴某某',
 '顺手',
 '拿起',
 '桌上',
 '的',
 '瓷碗',
 '向易',
 '某',
 '砸',
 '去',
 '，',
 '致使',
 '易',
 '某',
 '的',
 '脸部',
 '、',
 '耳朵',
 '等',
 '部位',
 '被',
 '划伤',
 '。',
 '后经',
 '鉴定',
 '，',
 '易',
 '某',
 '的',
 '伤情',
 '构成',
 '轻伤',
 '一级',
 '。',
 '公诉',
 '机关',
 '并',
 '提供',
 '了',
 '被害人',
 '的',
 '陈述',
 '、',
 '被告人',
 '的',
 '供述',
 '、',
 '证人',
 '的',
 '证言',
 '、',
 '伤情',
 '鉴定',
 '意见书',
 '等',
 '证据',
 '，',
 '以',
 '被告人',
 '吴某某',
 '犯',
 '×',
 '×',
 '向',
 '本院',
 '提起',
 '公诉',
 '，',
 '请求',
 '依法',
 '判处',
 '。',
 '\r\n']

# 词向量

In [29]:
embedding = TokenEmbedding(extended_vocab_path=SELF_DICT)

[2022-07-18 13:27:05,228] [    INFO] - Loading token embedding...
[2022-07-18 13:27:06,704] [    INFO] - Start extending vocab.
[2022-07-18 13:27:10,604] [    INFO] - Finish extending vocab.
[2022-07-18 13:27:18,877] [    INFO] - Finish loading embedding vector.
[2022-07-18 13:27:18,878] [    INFO] - Token Embedding info:             
Unknown index: 635964             
Unknown token: [UNK]             
Padding index: 635965             
Padding token: [PAD]             
Shape :[635966, 300]


# 测试词向量

In [30]:
embedding.search('黄某某')

array([[ 3.74482907e-02, -5.53701771e-03,  1.33492947e-01,
         1.37176156e-01,  7.42153749e-02, -2.20252462e-02,
         8.08257386e-02,  3.07918508e-02, -1.05136605e-02,
         7.76645914e-02, -1.12977311e-01,  4.40484695e-02,
         8.02873075e-03, -1.14350056e-03, -7.18081221e-02,
         1.11077346e-01, -5.58524691e-02, -8.49960521e-02,
        -1.13115251e-01,  1.02136254e-01, -5.37516288e-02,
         8.22900310e-02, -1.04653001e-01,  1.25295529e-02,
        -1.08212449e-01, -2.38671210e-02, -9.80639979e-02,
        -1.05529465e-01,  8.04895982e-02,  1.25723526e-01,
        -1.21570408e-01, -1.21442743e-01, -1.36753008e-01,
         2.41436884e-02, -1.28144771e-01, -6.51960121e-03,
         5.20986058e-02,  2.69391667e-02,  7.42391348e-02,
         2.56787408e-02,  6.16052561e-02,  9.16528702e-02,
        -2.80285664e-02,  5.17203957e-02, -2.22658180e-02,
         8.98989066e-02, -2.90975044e-03,  2.72365194e-02,
         9.83249471e-02,  8.35987972e-04,  1.36777058e-0

In [31]:
embedding.search('[UNK]')

array([[-0.01812284, -0.02110191,  0.00411597,  0.0076306 ,  0.01701404,
         0.0084905 ,  0.01932331, -0.01485573, -0.01407172, -0.03048673,
         0.05875535, -0.00285197,  0.01103535,  0.02508952, -0.01264112,
         0.0075718 ,  0.0120232 , -0.03577307,  0.00227025,  0.0079543 ,
         0.01644677,  0.01645847,  0.03126617, -0.03859777,  0.00986137,
        -0.00581434, -0.02331412, -0.01298439,  0.00889478,  0.00382191,
         0.03430478, -0.01562778, -0.00162941, -0.00732766, -0.01271996,
        -0.02726521, -0.00044824, -0.00675743,  0.0192259 ,  0.00101389,
         0.00667609, -0.01968822, -0.01899734,  0.02120117, -0.00687339,
         0.03628221,  0.00042425, -0.0293447 ,  0.02760715,  0.02237939,
        -0.0181015 , -0.00147023, -0.01486507, -0.00258962,  0.00284007,
        -0.05537624,  0.01107046, -0.01529494,  0.02002775,  0.00815979,
        -0.03765681,  0.00933891,  0.04110887, -0.01974672, -0.0385544 ,
         0.02275972, -0.00798539, -0.01966598,  0.0

In [36]:
embedding.search('易某')

array([[ 1.29958e-01, -5.68320e-02,  1.00183e-01, -3.95990e-02,
        -1.11897e-01, -1.88651e-01,  1.48032e-01, -1.30562e-01,
         1.27898e-01, -6.01650e-02,  7.42220e-02,  2.30577e-01,
        -5.44040e-02,  2.64677e-01, -1.80320e-02,  2.68168e-01,
         3.03038e-01,  3.38300e-02,  2.93480e-01, -1.10270e-02,
         2.60371e-01, -1.67004e-01, -1.14993e-01, -1.69730e-02,
        -3.71000e-03,  1.57394e-01,  3.62189e-01,  2.07151e-01,
         1.15954e-01,  1.02180e-01,  1.91711e-01, -6.98110e-02,
        -7.43250e-02, -8.81700e-03, -8.04000e-03,  7.82560e-02,
         1.59521e-01,  5.31830e-02,  1.00173e-01,  6.62800e-03,
        -1.88110e-02,  1.06283e-01,  1.13940e-02, -2.43138e-01,
        -8.37760e-02, -1.06429e-01, -2.06953e-01,  3.70210e-02,
         2.31968e-01, -2.43287e-01,  5.41440e-02,  2.36730e-01,
        -1.19272e-01, -2.35720e-02,  5.56080e-02, -7.35410e-02,
        -7.02970e-02, -1.65390e-01, -3.32989e-01,  1.00827e-01,
         9.81630e-02, -2.38614e-01, -3.1

In [43]:
embedding.weight.numpy()

array([[ 0.085129  ,  0.006704  , -0.029981  , ..., -0.030581  ,
         0.113344  , -0.01864   ],
       [ 0.03744829, -0.00553702,  0.13349295, ...,  0.11543085,
        -0.00888815, -0.06822342],
       [ 0.899245  ,  0.539141  ,  0.311919  , ...,  0.262844  ,
         0.112182  ,  0.107553  ],
       ...,
       [ 0.279822  , -0.091824  ,  0.01156   , ...,  0.101796  ,
         0.191216  ,  0.0547    ],
       [-0.01812284, -0.02110191,  0.00411597, ..., -0.02788694,
         0.02872122,  0.01064396],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]], dtype=float32)

In [52]:
embedding.search(tokenizer.cut(fact)).sum(axis=0)

(300,)